### ISSUE TITLE
Add support for send email to multiple email addresses

### ISSUE THREAD

**Issue by mkhodabandeh** [neilmunday/slurm-mail#11]

**Comment by neilmunday** [comment]
How would you like this to work? slurm-mail uses the value specified by `--mail-user` from Slurm. This parameter only accepts one e-mail address.

**Comment by neilmunday** [comment]
Closing issue due to no feedback.

**Comment by mafn** [comment]
It's possible to use multiple addresses separated by a comma in `--mail-user`. This however messes up the `To:` header and only sends out only one email. The second can be easily fixed by
```python
s.sendmail(email_from_address, user_email.split(','), msg.as_string())
```

**Comment by neilmunday** [comment]
Fixed in version 2.2, thanks for the info @mafn

**Comment by swvanderlaan** [comment]
Am I to understand that one can now do the following?

```
#SBATCH --mail-user=name1@someinstitute1.com,name2@someinstitute2.com
```

**Comment by neilmunday** [comment]
Correct as of Slurm-Mail version 2.2.
