### ISSUE TITLE
Emails are not sent for heterogeneous jobs

### ISSUE THREAD

**Issue by Aelmazaty** [neilmunday/slurm-mail#126]
**Versions**

OS version: Rocky 8.5
Slurm version: 23.02.7
Slurm Mail version: 4.10

**Describe the bug**

Hello,
Mails are not being received for Slurm heterogeneous jobs https://slurm.schedmd.com/heterogeneous_jobs.html
I've tested with the default mail client, I do get emails for this kind of jobs. However with slurm-mail I don't.
Thanks

**Logs**
For example this job
` sbatch -t "0-10" --mail-type=ALL -J "transform test 3 25g" --nodes 1 --cpus-per-task 3  --mem-per-cpu=512 : --nodes 1 --ntasks-per-node=1 --cpus-per-task=1 --mem-per-cpu=25G --wrap "hostname"`
slurm-mail logs show the jobs as "processed". However it seems they were never sent

**Comment by neilmunday** [comment]
Thanks for raising this issue. I am looking into it.

**Comment by neilmunday** [comment]
I've recreated the issue in Slurm-Mail 4.15 - I will work on a fix.

**Comment by neilmunday** [comment]
Note:

> Email notification for job state changes (the --mail-type option) is only supported for a heterogeneous job leader. Requests for email notifications for other components of a heterogeneous job will be silently ignored.

**Comment by neilmunday** [comment]
Version 4.16 released that includes support for heterogeneous jobs.

If you experience any problems with this new release, please let me know.
