### ISSUE TITLE
Job table prints "Memory per node" while the actul reported value is total memory

### ISSUE THREAD

**Issue by Aelmazaty** [neilmunday/slurm-mail#129]
**Versions**

OS version: Rocky 8.5
Slurm version: 23.02.7
Slurm Mail version: 4.16

**Describe the bug**

Hello,
The job table has "Memory per node" field. I believe this should be changed to totl requested memory
To reproduce the bug, try  `sbatch -N 2 --mem=4g -t 100 --mail-type=ALL  --wrap="sleep 1"` 
The job end mail would report 8G as the memory per node. However this is the total requested memory distributed over 2 nodes

**Logs**

Include any log snippets here - please used code tags.

**Comment by neilmunday** [comment]
Thank you for raising this issue. Version 4.17 has been released which fixes this issue by correcting the text used in the e-mails.
