### ISSUE TITLE
slurm_load_jobs error: Invalid job id specified

### ISSUE THREAD

**Issue by gmihaiescu** [neilmunday/slurm-mail#13]
The script used to work just fine but it stopped about 10 days ago and looking through the "/var/log/slurm-mail/slurm-send-mail.log" I noticed the following errors:

2020/12/03 11:21:03:INFO: processing: /var/spool/slurm-mail/702517.Ended.mail
2020/12/03 11:21:04:ERROR: failed to run: /usr/local/bin/scontrol -o show job=702517
2020/12/03 11:21:04:ERROR:
2020/12/03 11:21:04:ERROR: slurm_load_jobs error: Invalid job id specified

2020/12/03 11:21:04:INFO: sending e-mail to:  using xxx for job 702517 (Ended) via SMTP server smtp.gmail.com:587
2020/12/03 11:21:04:ERROR: failed to process: /var/spool/slurm-mail/702517.Ended.mail
2020/12/03 11:21:04:ERROR: Connection unexpectedly closed
Traceback (most recent call last):
  File "/opt/slurm-mail/bin/slurm-send-mail.py", line 546, in <module>
    s.login(smtpUserName, smtpPassword)
  File "/usr/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.6/smtplib.py", line 631, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/lib/python3.6/smtplib.py", line 421, in docmd
    return self.getreply()
  File "/usr/lib/python3.6/smtplib.py", line 394, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

The user's email address is correctly captured in the file "/var/spool/slurm-mail/702517.Ended.mail" 

It seems that the command to get the job details (/usr/local/bin/scontrol -o show job=702517) fails for jobs that finished, but it works fine for jobs that are still running:

# /usr/local/bin/scontrol -o show job=702588
slurm_load_jobs error: Invalid job id specified

# /usr/local/bin/scontrol -o show job=702514
JobId=702514 JobName=python UserId=XXX(10526) GroupId=XXX(10541) MCS_label=N/A Priority=2004244 Nice=0 Account=XXX QOS=normal JobState=RUNNING Reason=None Dependency=(null) Requeue=1 Restarts=0 BatchFlag=0 Reboot=0 ExitCode=0:0 RunTime=14:23:57 TimeLimit=UNLIMITED TimeMin=N/A SubmitTime=2020-12-02T20:59:27 EligibleTime=2020-12-02T20:59:27 AccrueTime=Unknown StartTime=2020-12-02T20:59:27 EndTime=Unknown Deadline=N/A PreemptTime=None SuspendTime=None SecsPreSuspend=0 LastSchedEval=2020-12-02T20:59:27 Partition=cpu AllocNode:Sid=q:1004 ReqNodeList=(null) ExcNodeList=(null) NodeList=cpu1 BatchHost=cpu1 NumNodes=1 NumCPUs=4 NumTasks=1 CPUs/Task=4 ReqB:S:C:T=0:0:*:* TRES=cpu=4,mem=16G,node=1,billing=7 Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=* MinCPUsNode=4 MinMemoryNode=16G MinTmpDiskNode=0 Features=(null) DelayBoot=00:00:00 OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null) Command=python WorkDir=XXX Power=

We are running Slurm 18.08 in this cluster but have same issue with the other cluster where we run slurm 19.05.3-2

**Comment by gmihaiescu** [comment]
I enabled smtp debugging and found out Gmail was complaining about "Too many login attempts, please try again later", the issue can be closed.

**Comment by neilmunday** [comment]
Hi @gmihaiescu. Glad you were able to resolve the issue. On the `slurm_load_jobs error: Invalid job id specified` front, Slurm-Mail uses information from `sacct` and `scontrol` to provide the information in the user e-mails. Job information from `scontrol` is only available for a limited time.

**Comment by KasperSkytte** [comment]
Would be nice with either a max number of retries, or even better a max number of mails to send at once to avoid rate-limiting. The `retryOnFailure` is insufficient in this matter. I'm limited to 10 mails per sec, so if there are more mails than that it can result in an infinite loop where `slurm-mail` keeps trying and the server keeps denying. Files just pile up and I have to clear the spool folder.

**Comment by neilmunday** [comment]
Hi. Thanks for the suggestion. I have created https://github.com/neilmunday/slurm-mail/issues/159 to track this feature request
