### ISSUE TITLE
When tail is enabled, any system user can  return any tailed file on the system on slurm controller

### ISSUE THREAD

**Issue by voodookungfoo** [neilmunday/slurm-mail#22]
Hi,

There is an issue in this package that If a normal user submits a SLURM job with a header as follows and "tail" enabled

#SBATCH -o /etc/shadow

then slurm-mail will email the user the tail contents of /etc/shadow, or any other file that the user should not have access to on the slurm controller they have specified with -o.

**Comment by dajamu** [comment]
Good spot @voodookungfoo. I'm a bit annoyed that I didn't see that one myself. I would have enjoyed the gloating rights over @neilmunday ;-)

**Comment by neilmunday** [comment]
@voodookungfoo I must echo @dajamu's comments, thanks for spotting and reporting the issue. I am embarassed this one slipped through.

Thank you to @dajamu for the quick fix and additional code improvements etc.

Version 2.3 now includes these.
