### ISSUE TITLE
Job Name not Parsed Properly

### ISSUE THREAD

**Issue by jitkang** [neilmunday/slurm-mail#24]
Greetings,

We just started implemented this into our HPC cluster, and everything works fine so far. Just one minor issue we have is the parsing of the job data.

The job name from the email are shown as followed where there is a `|` character at the end of the job name:

Name:	mail_test|

After digging into the script, we found that one simple changes can be done to remove the `|` character, which is to change the parameter `-p` into `-P` in `slurm-send-mail.py` under `process_spool_file` function:

`cmd = (f"{sacct_exe} -j {first_job_id} -P -n --fields={field_str}")`

This remove the pipe ending of the output, and thus eliminate the `|` character in the email sent.

**Comment by neilmunday** [comment]
Hi @jitkang.

Thanks for reporting the issue and for the fix. I've tested the modifcation and release version 2.4 of Slurm Mail which includes the fix.

Cheers,

Neil.
