### ISSUE TITLE
get_kbytes_from_str: unknown unit 'C' for value '0c'

### ISSUE THREAD

**Issue by matteoguglielmi** [neilmunday/slurm-mail#38]
Hello,

I'm running version 3.1 of slurm-mail with **verbose=true** set in **slurm-mail.conf**.

Does anybody know what is the ERROR message (from **slurm-send-mail.log**) reported here below?

Thank you!

```
2022/05/18 12:35:01:ERROR: get_kbytes_from_str: unknown unit 'C' for value '0c'
2022/05/18 12:35:01:DEBUG: Running /usr/local/bin/scontrol -o show job=33837
2022/05/18 12:35:01:DEBUG: Creating template for job 33837
2022/05/18 12:35:01:DEBUG: Creating e-mail signature template
2022/05/18 12:35:01:INFO: Sending e-mail to: XXXX using XXXX@XXXX.XX for job 33837 (Ended) via SMTP server smtps.XXXX.XX:587
2022/05/18 12:35:01:INFO: Deleting: /var/spool/slurm-mail/33837_1652870050.0510437.mail
2022/05/18 12:36:01:INFO: processing: /var/spool/slurm-mail/33838_1652870160.1111429.mail
2022/05/18 12:36:01:DEBUG: Running /usr/local/bin/sacct -j 33838 -P -n --fields=JobId,User,Group,Partition,Start,End,State,ReqMem,MaxRSS,NCPUS,TotalCPU,NNodes,WorkDir,Elapsed,ExitCode,Comment,Cluster,NodeList,TimeLimit,TimelimitRaw,JobIdRaw,JobName
2022/05/18 12:36:01:DEBUG: 33838|XXXX|XXXXXXXXXX|1652870039|1652870160|COMPLETED|0c||1|00:00.018|1|/cluster/home/staff/XXXX/unix/tmp|00:02:01|0:0||cluster|node49|10:10:00|610|33838|TEST
33838.batch||||1652870039|1652870160|COMPLETED|0c|472K|1|00:00.018|1||00:02:01|0:0||cluster|node49|||33838.batch|batch
33838.extern||||1652870039|1652870160|COMPLETED|0c|0|1|00:00:00|1||00:02:01|0:0||cluster|node49|||33838.extern|extern
```

**Comment by neilmunday** [comment]
Hi @matteoguglielmi thank you for the information. Are you able to show the messages in the log preceeding the error? In verbose mode the log should show the `sacct` command that was run and the the output. That may help track down the cause of the issue.

**Comment by dajamu** [comment]
@neilmunday check out this commit:

https://github.com/SchedMD/slurm/commit/2acdf51e9e1fde8fe28dce847aa769e0f6455e60

Looks like the ReqMem value used to always be in Megabytes (i.e. no unit specified) but with a 'c' or 'n' suffix to indicate either Memory per CPU or Memory per Node.

**Comment by matteoguglielmi** [comment]
Hi @neilmunday,

slurm version is 20.11.8 and no mem option is used by the user.

In slurm.conf, DefMemPerCPU=0

Hop this helps.

**Comment by neilmunday** [comment]
@dajamu thanks for tracking down the cause and to @matteoguglielmi for confirming it's a Slurm 20 feature. I've only tested Slurm Mail 3.0 onwards with Slurm 21 so I'll create a Slurm 20 test environment.

@matteoguglielmi you might want to update from Slurm 20.11.8 to 20.11.9 due address some big CVEs that were disclosed recently. For further details, see: https://schedmd.com/news.php -> scroll to 4th May news item.

**Comment by neilmunday** [comment]
@matteoguglielmi I have implemented a fix in the `main` branch if you would like to give it a try?

**Comment by sdx23** [comment]
I have tested this, and it works - kind of. The "c" suffix means "per-cpu" so technically the value should be multiplied by self.cpus, which at this point is unfortunately not so easy to do.

**Comment by neilmunday** [comment]
> I have tested this, and it works - kind of. The "c" suffix means "per-cpu" so technically the value should be multiplied by self.cpus, which at this point is unfortunately not so easy to do.

This is true. I have added a code to handle this is commit 3b4e99a06b6f7b9d64790e4fd3e8a029092c8b70

**Comment by matteoguglielmi** [comment]
@neilmunday,

thanks for the patch which works!

`2022/05/25 10:57:01:DEBUG: Applying ReqMem workaround for Slurm versions < 21`

**Comment by neilmunday** [comment]
@matteoguglielmi thanks for the feedback - glad to hear it works.
