### ISSUE TITLE
KeyError: 'StdErr' with srun

### ISSUE THREAD

**Issue by mafn** [neilmunday/slurm-mail#42]
**Versions**

OS version: Alma Linux 8.6
Slurm version: 20.11.9
Slurm Mail version: main (ca49444)

**Describe the bug**
Starting an interactive (but for some reason mail sending) job with `srun --mail-type=...` won't send mails
**Logs**
```
2022/06/20 17:28:01:ERROR: Failed to process: /var/spool/slurm-mail/67116962_1655738726.7596319.mail
2022/06/20 17:28:01:ERROR: 'StdErr'
Traceback (most recent call last):
  File "/opt/slurm-mail/bin/slurm-send-mail.py", line 827, in <module>
    process_spool_file(f, smtp_conn)
  File "/opt/slurm-mail/bin/slurm-send-mail.py", line 501, in process_spool_file
    job.stderr = scontrol_dict['StdErr']
KeyError: 'StdErr'
```

That happens because `srun`-jobs don't seem to have `StdErr`, `StdIn` and `StdOut` set:
```
Command=hostname
WorkDir=/home/example
Power=
MailUser=example
```
compared to using sbatch:
```
Command=/home/example/testscript.sh
WorkDir=/home/example/
StdErr=/home/example/slurm/output67116921_1.out
StdIn=/dev/null
StdOut=/home/example/slurm/output67116921_1.out
Power=
MailUser=example
```

**Comment by neilmunday** [comment]
@mafn thanks for reporting this bug. I have confirmed that this is indeed a bug and will work on a fix.

**Comment by neilmunday** [comment]
Version 3.4 released with fix in place. Thanks again for reporting.
