### ISSUE TITLE
Slurm does not send email at any state(Failed or BEGIN)

### ISSUE THREAD

**Issue by shirof30** [neilmunday/slurm-mail#44]
**Versions**

OS version: 18.04.6 LTS 
Slurm version: 22.05.2
Slurm Mail version: 3.5

**Describe the bug**

I reconfigured slurm.conf to point to the location of the mailprog, however on the logs it doesnt show that the python script itself is being called at any state. I tried running directly using `python3 slurm-spool-mail.py` and it shows invalid number of arguments, and the error was logged at the logfile. Hence I realized that slurm cannot call the python script, is there a test command line that I can test to see if the script itself is working? Thanks

**Comment by neilmunday** [comment]
Hi,

As `slurm-spool-mail.py` works from the command line that is a good sign at least that your python set-up is ok.

Are there any errors reported in the `slurmctld` logs?

Also, can you confirm that jobs are being submitted with the `--mail-type` option set?

Thanks,

Neil.

**Comment by shirof30** [comment]
slurmcltd.log shows error as follows :
[2022-07-27T13:27:28.920] slurmscriptd: error: run_command: MailProg can not be executed (/mnt/ceph/legion/slurm-mail-main/bin/slurm-spool-mail.py) Permission denied
[2022-07-27T13:27:28.920] slurmscriptd: error: _run_script: JobId=0 MailProg exit status 0:127
[2022-07-27T13:27:28.921] error: MailProg returned error, it's output was 'Run command failed - configuration error'

however, the permissions I already changed as follows 👍 
drwxrwxr-x 2 slurm slurm 35911 Jul 22 14:03 bin
drwxrwxr-x 5 slurm slurm  9135 Jul 22 14:03 build
-rw-rw-r-- 1 slurm slurm  4601 Jul 21 19:00 CHANGELOG.md
-rw-rw-r-- 1 slurm slurm    15 Jul 21 19:00 CODEOWNERS
drwxrwxr-x 3 slurm slurm  5457 Jul 22 14:03 conf.d
-rw-rw-r-- 1 slurm slurm 35147 Jul 21 19:00 LICENSE
drwxrwxr-x 2 slurm slurm    78 Jul 22 14:03 logrotate.d
-rw-rw-r-- 1 slurm slurm 17299 Jul 21 19:00 README.md
-rw-rw-r-- 1 slurm slurm  3021 Jul 21 19:00 slurm-mail.spec
drwxrwxr-x 2 slurm slurm 22278 Jul 22 14:03 tests
-rw-rw-r-- 1 slurm slurm     4 Jul 21 19:00 VERSION
nvme@SERVER:/mnt/ceph/legion/slurm-mail-main$ cd bin
nvme@SERVER:/mnt/ceph/legion/slurm-mail-main/bin$ ls -l
total 36
-rw-rw-r-- 1 slurm slurm 30350 Jul 21 19:00 slurm-send-mail.py
-rw-rw-r-- 1 slurm slurm  5561 Jul 22 14:05 slurm-spool-mail.py

**Comment by neilmunday** [comment]
Thanks for the logs. I think this will do the trick:

```bash
chmod 755 /mnt/ceph/legion/slurm-mail-main/bin/*.py
```

**Comment by shirof30** [comment]
Hi there, seems to work but still not getting mails. 
slurmctld log has no errors, and mails are in the spool folder.

/var/log/slurm-mail/slurm-spool-mail.log
2022/07/29 13:32:51:INFO: writing file: /var/spool/slurm-mail/88868_1659115971.$



/var/spool/slurm-mail# ls
88851_1659115961.5236294.mail  88868_1659115971.2994804.mail
88851_1659115961.526617.mail

**Comment by neilmunday** [comment]
Have you set-up the cron job as described here: https://github.com/neilmunday/slurm-mail#source-installation ?

**Comment by shirof30** [comment]
> Have you set-up the cron job as described here: https://github.com/neilmunday/slurm-mail#source-installation ?

apparently I mistyped some items in the cron job. should be fixed for now :) will let you know if any issue appears

**Comment by shirof30** [comment]
cron job is set, 

slurm send mail log is
2022/08/03 17:30:24:INFO: processing: /var/spool/slurm-mail/88851_1659115961.526617.mail
2022/08/03 17:30:25:INFO: processing: /var/spool/slurm-mail/88851_1659115961.526617.mail
2022/08/03 17:34:36:INFO: processing: /var/spool/slurm-mail/89140_1659562476.6142197.mail
2022/08/03 17:34:38:INFO: processing: /var/spool/slurm-mail/89140_1659562476.6142197.mail

but still no mail regarding that job#, any tips ?

**Comment by neilmunday** [comment]
The error messages above imply that `slurm-send-mail.py` was unable to connect to your SMTP server. Have you set one up? If so, please check the details are correct in `/opt/slurm-mail/conf.d/slurm-mail.conf` in the `[slurm-send-mail]` section of this file.

Also see: https://github.com/neilmunday/slurm-mail#smtp-settings

Hope this helps.

**Comment by shirof30** [comment]
Just wondering if SMTP requires postfix to be installed?

**Comment by neilmunday** [comment]
`postfix` provides an SMTP server. It's one of the most widely ones used. Alternatively, you can also configure Slurm-Mail to send e-mails via Google's SMTP server using your GMail credentials.
