### ISSUE TITLE
Handle mail errors without infinite resend

### ISSUE THREAD

**Issue by jcklie** [neilmunday/slurm-mail#54]
Thanks for this awesome project! It was really easy to set up using your detailed documentation and I enjoy the much richer information now. I ran into a small issue when using this, as I send mails via an internal relay that only accepts mail to addresses in the form of @my-university.com. This causes now the issue that slurm-mail dies when sending to valid but outside addresses and tries to resend every minute. I thought of the following fixes:

1. Expose the mail regex so it is user configurable (just solves my issue)
2. Make deleting job spools on (smtp) errors configurable

I do not know what a good solution is, I think the first one is better. If you agree, then I can also send a PR.

**Comment by neilmunday** [comment]
I agree, I think option 1 is the way to go. I've just push a commit to the 4.1 branch if you'd like to give it a try?

**Comment by jcklie** [comment]
It works for me, thanks!

**Comment by neilmunday** [comment]
Excellent - thanks for testing.

I will updated the `README` for the next release in due course.
