### ISSUE TITLE
cron.d files not used in Centos 7

### ISSUE THREAD

**Issue by jcklie** [neilmunday/slurm-mail#55]
**Versions**

OS version: Centos 7
Slurm version: 22.05.2
Slurm Mail version: 4.0

**Describe the bug**

The slurm-mail job in cron.d is not picked up. After I add a newline to the file, then it works. In the internet, there are some pages which told me that. It is a really arcane issue and a nasty bug, as I did not see any log output telling me that.

[1]: https://superuser.com/questions/1059775/cron-apparently-requires-a-newline-character-on-its-own-line-at-the-end-of-the-f
[2]: https://cronitor.io/cron-reference/missing-newline-before-eof

**Comment by neilmunday** [comment]
Thanks for finding and fixing this issue. Pull request now merged into new 4.1 branch.
