### ISSUE TITLE
Cannot build RPM on CentOS with new version if slurmmail is already installed

### ISSUE THREAD

**Issue by jcklie** [neilmunday/slurm-mail#57]
**Versions**

OS version: Centos 7
Slurm Mail version: 4.1 

**Describe the bug**

I tried building a 4.1 rpm on my slurm login node where slurmmail 4.0 is installed. I cloned the repository, built my RPM but it used as version 4.0. This was strange so debugging lead me to the following: The `get-property.py` and `process-template.py`include `slurmmail`, but because we append to sys.path instead of prepending, the globally installed slurmmail is found first so it uses `VERSION=4.0` and not `VERSION=4.1`.

This can be tested by having a RHEL node where slurmmail is installed and running `get-property.py version`.

The fix is easy, one just needs to prepend to sys instead of appending, I will send a PR once I am on my PC at home.

**Comment by neilmunday** [comment]
Fixed by pull request #59 which has been merged.
