### ISSUE TITLE
Cannot make slurm-mail send emails

### ISSUE THREAD

**Issue by asterismo** [neilmunday/slurm-mail#6]
if i execute /usr/bin/python /opt/slurm-mail/bin/slurm-send-mail.py nothing happens, any ideas? after launching a slurm job, no log activity, no emails.

**Comment by neilmunday** [comment]
Hi. Are any log files written to: /var/log/slurm-mail ?

**Comment by asterismo** [comment]
Not at all!

**Comment by neilmunday** [comment]
The `slurm-send-mail.py` script examines the contents of `/var/spool/slurm-mail` for files created by `slurm-spool-mail.py`. Are there any files in this directory? If there are none, then the script will just exit as it has nothing to do.

We need to confirm that `slurm-spool-mail.py` is working. Can you confirm that you have set `MailProg` correctly in `slurm.conf` and restarted `slurmctld` ?

Also in your Slurm jobs have you set the `--mail-type` and `--mail-user` options also to tell Slurm to send e-mail notificiations? If you have not set `--mail-type` then Slurm will not send e-mail notifications for jobs.

**Comment by asterismo** [comment]
/var/spool/slurm-mail is empty

I restarted slurmctld

MailProg=/opt/slurm-mail/bin/slurm-spool-mail.py

SBATCH --mail-user=mymail@mydomain.com
SBATCH --mail-type=ALL

Still no sending mail attempt (also watching /var/log/mail/mail.log)

**Comment by neilmunday** [comment]
What happens if you run `/opt/slurm-mail/bin/slurm-spool-mail.py` - do you get any errors?

**Comment by neilmunday** [comment]
Do you have selinux enabled? If so, try running `setenforce 0` to temporarily disable it and try again.

You could also try changing this line in `slurm-spool-mail.py` from:

```
logging.basicConfig(format='%(asctime)s:%(levelname)s: %(message)s', datefmt='%Y/%m/%d %H:%M:%S', level=logging.DEBUG, filename=logFile)
```

To:

```
logging.basicConfig(format='%(asctime)s:%(levelname)s: %(message)s', datefmt='%Y/%m/%d %H:%M:%S', level=logging.DEBUG)
```

Now try running the script again. This will cause log output to go to standard out instead of the log file.

**Comment by asterismo** [comment]
setenforce: command not found

**Comment by asterismo** [comment]
root@cebollati:/opt/slurm-mail/bin# ./slurm-spool-mail.py 
2020/04/03 19:54:53:DEBUG: called with: ['./slurm-spool-mail.py']
2020/04/03 19:54:53:ERROR: list index out of range
root@cebollati:/opt/slurm-mail/bin# python3 slurm-spool-mail.py 
  File "slurm-spool-mail.py", line 53
    print msg
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?
root@cebollati:/opt/slurm-mail/bin#

**Comment by asterismo** [comment]
root@cebollati:/opt/slurm-mail/bin# python slurm-spool-mail.py 
2020/04/03 19:55:32:DEBUG: called with: ['slurm-spool-mail.py']
2020/04/03 19:55:32:ERROR: list index out of range

**Comment by neilmunday** [comment]
From the output you have posted, it looks like you are using an older version of Slurm-Mail. Please make sure you are using the latest version which has Python 3 support.

**Comment by neilmunday** [comment]
Closing issue
