### ISSUE TITLE
 Slurm Results E-Mail cannot resolve node name?

### ISSUE THREAD

**Issue by jcklie** [neilmunday/slurm-mail#60]
**Versions**

OS version: Centos 7
Slurm version: 22.05
Slurm Mail version: 4.1 Snapshot

**Describe the bug**

It looks like some variables cannot be resolved when looking up results files.

**Logs**

```
The last 25 lines of /x/y/f1000_transformer/logs/F1000_Training_F1000_Training.31224.%N.log are shown below:

slurm-mail: file /x/y/f1000_transformer/logs/F1000_Training_F1000_Training.31224.%N.log does not exist
```

**Comment by jcklie** [comment]
My colleague reported it by himself in #61 , sry for the duplicate!

**Comment by neilmunday** [comment]
> I hope you do not mind my many bug reports, it means that we actually use your awesome tool!

Not at all - glad you are getting some good use out of it :-)
