### ISSUE TITLE
Slurm-mail sends contradictiory emails (subject says 'cancelled', body 'begin')

### ISSUE THREAD

**Issue by jcklie** [neilmunday/slurm-mail#65]
**Versions**

OS version: Centos 7
Slurm version: 22.05
Slurm Mail version: 4.1 Snapshot

**Describe the bug**

Slurm-mail sends contradictiory emails (subject says 'cancelled', body 'begin')

```
From: UKP Slurm <slurmulon@ukp.informatik.tu-darmstadt.de>
Subject: UKP Slurm - Job 31928: **cancelled**
Date: 7. November 2022 at 2:52:05 PM CET
To: <xyz>

Dear X,
Your job 31928 has **started** on ukp-cluster.
Details about the job can be found in the table below:
```

**Logs**

The slurm-mail log says the job started. I think the job waited a bit in the queue before it got to run.

**Comment by neilmunday** [comment]
Thanks for reporting the issue.

I think this block of code is to blame:

```python
        if not job.did_start or (job.state is not None and "CANCELLED" in job.state):
            subject_state = "cancelled"
        else:
            subject_state = state
```

I'll investigate...

**Comment by neilmunday** [comment]
Commits submitted which squash this bug. Thanks for reporting.
