### ISSUE TITLE
Convert username to email

### ISSUE THREAD

**Issue by simonleary-umass-edu** [neilmunday/slurm-mail#68]
The default email for slurm is just the username, if I'm not mistaken. I can go from username to email via python ldap.

Is this something that can be done? Where exactly in the existing code should I add such a feature?

**Comment by neilmunday** [comment]
Hi,

You can use `sbatch` option `--mail-user` to specify the e-mail address to send job notifications about a particular job to, e.g. 

```
#SBATCH --mail-user=john.doe@example.com
```

Another alternative is to configure your email server to look-up e-mails addresses from LDAP. For example, `postfix` supports this. See https://www.postfix.org/LDAP_README.html

This has the benefit of working not just for Slurm-Mail but also for other services on your next work.

**Comment by simonleary-umass-edu** [comment]
My goal was to remove the need to users to type `--mail-user`.

I'll look into postfix, that might work.

I take it that there is no good place in the existing code for such a feature?

**Comment by neilmunday** [comment]
If you can get postfix and LDAP configured you will find it will make your life easier in the long run.

If you were to modify the Slurm-Mail source to add in the use of python-ldap, then somewhere before [this line](https://github.com/neilmunday/slurm-mail/blob/main/src/slurmmail/cli.py#L470) you would need to add code to perform the LDAP look-ups.

**Comment by simonleary-umass-edu** [comment]
Thanks!

**Comment by simonleary-umass-edu** [comment]
I setup postfix Ldap, but slurm-mail requires that the recipient fits some email regex:
https://github.com/neilmunday/slurm-mail/blob/0bcec73ea7de471c85a46f4dbc8ea597bcd250c5/src/slurmmail/cli.py#L146

**Comment by neilmunday** [comment]
Have you set `validateEmail` to `true` in `/etc/slurm-mail/slurm-mail.conf`?

If so, set this to `false`.

For further info, please see [Validating E-mails](https://github.com/neilmunday/slurm-mail/#validating-e-mails).

**Comment by simonleary-umass-edu** [comment]
set to `false`, thanks again

**Comment by neilmunday** [comment]
No worries, glad that did the trick :-)
