### ISSUE TITLE
Deb package installs fail on Ubuntu

### ISSUE THREAD

**Issue by sfeltman** [neilmunday/slurm-mail#72]
**Versions**

OS version: Ubuntu 20.04
Slurm version: 21.08.8-2
Slurm Mail version: HEAD @ 32f9f31

**Describe the bug**

Custom built deb package fails to install cleanly. This is due to `slurm-mail.postinst` specifying `#!/usr/bin/bash` which doesn't exist on Ubuntu 20.04. Could this be changed to `#!/usr/bin/env bash` for portability?

**Logs**

Setting up slurm-mail (4.2-ubuntu1) ...
dpkg (subprocess): unable to execute installed slurm-mail package post-installation script (/var/lib/dpkg/info/slurm-mail.postinst): No such file or directory
dpkg: error processing package slurm-mail (--configure):
 installed slurm-mail package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 slurm-mail

**Comment by neilmunday** [comment]
@sfeltman thank you for raising this issue.

I have pushed a fix to the new [72-deb-package-installs-fail-on-ubuntu branch](https://github.com/neilmunday/slurm-mail/tree/72-deb-package-installs-fail-on-ubuntu).

Are you able to confirm this works for you please?

**Comment by sfeltman** [comment]
Hi @neilmunday 

Thanks for the fast response. I confirmed this builds and installs on Ubuntu 20.04 now. I'm manually running `build-tools/build-deb.sh` on an Ubuntu 20.04 system.

There still seems to be other issues which I can log separately (`/etc/cron.d/slurm-mail` and `etc/logrotate.d/slurm-mail` are not getting installed but the folders are created)

**Comment by neilmunday** [comment]
It's ok, let's keep the Ubuntu 20.04 issues in this ticket. I'll see if I can get an Ubuntu 20.04 environment set-up to look into these issues further.

**Comment by sfeltman** [comment]
I ended up logging <https://github.com/neilmunday/slurm-mail/issues/73> before seeing your note. There is a bunch of info in there.

**Comment by neilmunday** [comment]
No problem 👍

**Comment by neilmunday** [comment]
Fixed in 4.3 branch.
