### ISSUE TITLE
Issues installing and using slurm-mail cron on Ubuntu 20.04

### ISSUE THREAD

**Issue by sfeltman** [neilmunday/slurm-mail#73]
**Versions**

OS version: Ubuntu 20.04
Slurm version: 21.08.8
Slurm Mail version: HEAD @ fd79873

**Describe the bug**

apt install with deb package doesn't write `/etc/cron.d/slurm-mail/slurm-mail` or `/etc/logrotate.d/slurm-mail/slurm-mail`.
However, running with `dpkg --force-all` works.

```
# apt install /tmp/slurm-mail_4.2-ubuntu1_all.deb
...
Setting up slurm-mail (4.2-ubuntu1)
W: Repository is broken: slurm-mail:amd64 (= 4.2-ubuntu1) has no Size information

# echo $?
0
```

Not sure if the repository size warning has anything to do with the issue but the install was successful. Now see this:

```
# ls /etc/cron.d/slurm-mail/slurm-mail
ls: cannot access '/etc/cron.d/slurm-mail/slurm-mail': No such file or directory
# ls /etc/logrotate.d/slurm-mail/slurm-mail
ls: cannot access '/etc/logrotate.d/slurm-mail/slurm-mail': No such file or directory
```

The following works around the issue:
```
dpkg --force-all -i  slurm-mail_4.2-ubuntu1_all.deb
...
# ls /etc/cron.d/slurm-mail/slurm-mail
/etc/cron.d/slurm-mail/slurm-mail
```

Additionally, `/etc/cron.d/slurm-mail/slurm-mail` seems to be an invalid location on Ubuntu. Once installed the cron is never triggered. According to <https://superuser.com/questions/452085/is-it-possible-to-add-directories-under-cron-d#answer-452250>, it is not possible to nest sub-folders under `/etc/cron.d/`. Moving the `slurm-mail` file out of the sub-folder to fixes the issue.

**Comment by neilmunday** [comment]
I've reproduced the issue using an Ubuntu 20.04 container.

Also, configuration files are not created under `/etc/slurm-mail`.

**Comment by neilmunday** [comment]
@sfeltman I've created a [4.3 branch](https://github.com/neilmunday/slurm-mail/tree/4.3) which includes fixes for issue #72 and this issue.

This branch includes support for Ubuntu 20.04 and I've added a `check-deb.sh` script to the Docker based build process which tests installing the generated package and checks that the config files and scripts are installed.

Would you be able to test the branch to confirm it works for you please?

E.g.

```
git clone https://github.com/neilmunday/slurm-mail.git
cd slurm-mail
git checkout 4.3
build-tools/build-deb.sh
```

**Comment by sfeltman** [comment]
@neilmunday, thank you. I will test this tomorrow.

**Comment by sfeltman** [comment]
@neilmunday, I ran into a couple of issues:

`build-tools/build-deb.sh` was hitting an error running on bare metal, perhaps I'm missing a dep:

```
dh_auto_install: error: pybuild --install -i python{version} -p 3.8 --dest-dir /tmp/tmp.rQhb9r0upX/slurm-mail-4.3/debian/slurm-mail returned exit code 13
make: *** [debian/rules:7: binary] Error 13
```

I was able to use `build-tools/Ubuntu_20.04/build.sh` to generate the deb. The resulting package wasn't installing templates with `apt`, but `dpkg --force-all -i` again worked around that issue.

**Comment by neilmunday** [comment]
When running on brare metal, do you have the following packages installed?:

* fakeroot
* dh-python
* lintian
* lsb-release
* python3
* python3-all
* python3-stdeb

It would seem that install the Debian package using `apt-get` works fine on a vanilla Ubuntu install, but if you uninstall the package and then install again using `apt-get` it does not work properly.

I will continue to investigate.

**Comment by neilmunday** [comment]
For Ubuntu 20.04 I think we might be hitting this bug when installing from a package file: https://salsa.debian.org/apt-team/apt/-/merge_requests/177

**Comment by neilmunday** [comment]
I think using `dpkg --force-all -i` is the best way to install Slurm-Mail from a Debian package. I've updated the README with this info.

I've also updated the 4.3 branch to add a `slurm-mail.postrm` script to remove the logrotate and cron files when the package is removed.

**Comment by neilmunday** [comment]
Would you be happy for this issue to be closed?

**Comment by sfeltman** [comment]
Hi @neilmunday, I think it is ok to close this. Will you be releasing .deb files for Ubuntu 20.04?

**Comment by neilmunday** [comment]
Version 4.3 has been released which includes pre-built packages for Ubuntu 20 and 22.
