### ISSUE TITLE
Incorrect JOB_NAME in subject and body

### ISSUE THREAD

**Issue by sfeltman** [neilmunday/slurm-mail#75]
**Versions**

OS version: Ubuntu 20.04
Slurm version: 21.08.8-2
Slurm Mail version: HEAD @32f9f31

**Describe the bug**

JOB_NAME seems to always appear as "allocation" instead of the actual job name.

Email subject was setup as: `emailSubject = Job $JOB_NAME ($JOB_ID): $STATE`

Resulting email shows "allocation" for the job name in the subject (and body): "Job allocation (2467): Ended"

**Logs**

```
2023/03/01 01:14:01:DEBUG: Called with: ['/usr/bin/slurm-spool-mail', '-s', 'Slurm Job_id=2467 Name=tmpmi43oxw_.sh Ended, Run time 00:00:01, COMPLETED, ExitCode 0', '...']
2023/03/01 01:14:01:DEBUG: info str: Slurm Job_id=2467 Name=tmpmi43oxw_.sh Ended
```

**Comment by neilmunday** [comment]
As a test, I have tried repeating the issue under Rocky 8 using Slurm 21.08.8-2 with Slurm-Mail 4.2 and 4.3 and I cannot repeat the issue.

Are you able to share the `sbatch` options used with the job script `tmpmi43oxw_.sh`?

I will try to test with Ubuntu 20.04 also.

**Comment by sfeltman** [comment]
The cmdline would have been something like: `sbatch --ntasks 1 --cpus-per-task 1 --mail-user <...> ---mail-type END,FAIL /tmp/tmpmi43oxw_.sh`

That being said, I can't reproduce the problem today.

**Comment by neilmunday** [comment]
I'm not sure how to proceed with this one as I have been unable to recreate the issue.

Have you had any other instances of the issue?

**Comment by sfeltman** [comment]
Thanks for checking in with this. I retested after installing the newly release 4.3 package for Ubuntu 20 and it wasn't reproducible.
