### ISSUE TITLE
Mail not being sent on  Ubuntu 20.04

### ISSUE THREAD

**Issue by rggs** [neilmunday/slurm-mail#81]
**Versions**

OS version: Ubuntu 20.04
Slurm version: slurm 22.05.2
Slurm Mail version: 4.4

**Describe the bug**

I installed Slurm Mail with the .deb package, edited the config file, and can see the cron job running and emails being added to the spool dir and spool log. However, I never receive the emails, and the send-mail log remains empty. I am able to send mail from the server via sendmail and have confirmed that port 25 is open between our server and the mail server.

**Logs**

slurmctl.log
```
[2023-03-28T14:09:06.068] _slurm_rpc_submit_batch_job: JobId=453 InitPrio=4294901687 usec=544
[2023-03-28T14:09:06.458] sched/backfill: _start_job: Started JobId=453 in batch on GPU-SERVER
[2023-03-28T14:09:07.632] _job_complete: JobId=453 WEXITSTATUS 0
[2023-03-28T14:09:07.633] _job_complete: JobId=453 done
```
cron logs
```
Mar 28 14:07:01 SLURM-HEAD-NODE CRON[1000350]: (root) CMD (   /usr/bin/slurm-send-mail)
Mar 28 14:07:03 SLURM-HEAD-NODE sSMTP[1000449]: Sent mail for root@OURDOMAIN.COM (221 2.0.0 PLOPPAGENT02.OUR.RESOURCE.DOMAIN.COM closing connection) uid=0 username=root outbytes=739
Mar 28 14:07:03 SLURM-HEAD-NODE CRON[1000348]: pam_unix(cron:session): session closed for user root
```
spool-mail.log
```
2023/03/28 14:09:07:DEBUG: Called with: ['/usr/bin/slurm-spool-mail', '-s', 'Slurm Job_id=453 Name=mail_test Ended, Run time 00:00:01, COMPLETED, ExitCode 0', 'MY_EMAIL@ME.com']
2023/03/28 14:09:07:DEBUG: info str: Slurm Job_id=453 Name=mail_test Ended
2023/03/28 14:09:07:DEBUG: Job ID: 453
2023/03/28 14:09:07:DEBUG: State: Ended
2023/03/28 14:09:07:DEBUG: Array Summary: False
2023/03/28 14:09:07:DEBUG: E-mail to: MY_EMAIL@ME.com
2023/03/28 14:09:07:INFO: writing file: /var/spool/slurm-mail/453_1680012547.8007495.mail
```
And of course nothing in the send-mail.log

**Comment by neilmunday** [comment]
Hi,

Thanks for providing a detailed description.

To debug the issue further, can you try:

1.  Comment the `logFile` line in `/etc/slurm-mail/slurm-mail.conf`
2. Assuming there are files in `/var/spool/slurm-mail`, execute as root: `/usr/bin/slurm-send-mail -v`

This should cause `slurm-send-mail` to write any output and errors to the console. If so, can you tell me what they are please?

**Comment by rggs** [comment]
Ah perfect! I wish I'd known to comment out the log file sooner to test it. So here was the issue I saw after following those steps:
```
$ sudo /usr/bin/slurm-send-mail -v
ERROR:root:Error: No option 'smtpusername' in section: 'slurm-send-mail'
Error: No option 'smtpusername' in section: 'slurm-send-mail'
```
We have an internal mail server that doesn't require authentication, so I had left the smtpUserName and password fields commented out. I uncommented them, added root as the smtp user, and it's now working!

For what it's worth, it might be helpful to add a quick blurb into the readme about troubleshooting with the tips on uncommenting the `logFile` argument and running `/usr/bin/slurm-send-mail` with the `-v` flag. I tried to run `/usr/bin/slurm-send-mail` and root, but because I didn't do the other steps I never saw the errors.

Thanks for the help @neilmunday!

**Comment by neilmunday** [comment]
@rggs glad the info helped. Following your suggestion I've added a troubleshooting section to the README.

If your SMTP server does not require a login, you should be able to leave `smtpUserName` and `smtpPassword` set to null, i.e.

```
smtpUserName =
smtpPassword =
```
