### ISSUE TITLE
slurm-mail and slurm-ohpc

### ISSUE THREAD

**Issue by arm2arm** [neilmunday/slurm-mail#88]
Is slurm-mail compatible with slurm-ohpc-22.05.2-14.1.ohpc.2.6.x86_64.rpm?
thank you beforehand.

**Comment by neilmunday** [comment]
Hi @arm2arm. Although I have not tested with `slurm-ohpc-22.05.2-14.1.ohpc.2.6.x86_64.rpm` as this is using Slurm 22 which Slurm-Mail is tested against, I see no reason why it would not work.
