### ISSUE TITLE
remove depends on slurmctld

### ISSUE THREAD

**Issue by mrgum** [neilmunday/slurm-mail#92]
**Versions**

OS version: el7/8/9 sle
Slurm version: any
Slurm Mail version: git main branch

**Describe the bug**

The spec file has depends on slurmctld (for elX) and slurm (for sle) This means that when you install slurm-mail rpms slurmctld, slurm and munge all get installed from whichever out of date version your dist has. If you have installed slurm manually or use something like parallelcluster that breaks things.

slurm-mail does NOT depend on slurm, it could work perfectly well without it, albeit the primary use of slurm-mail is which slurm, however I'd say slurmctld optionally depends on slurm-mail **NOT** the other way around.

PR on its way

**Logs**

Include any log snippets here - please used code tags.

**Comment by neilmunday** [comment]
@mrgum thanks for creating the issue and the associated pull request. I agree, I can see how this could be a problem for users that do not use a RPM based installation of Slurm.

Your pull request has been merged into the 4.5 branch and I have also made a similar modification for the Debian/Ubuntu control file.

**Comment by neilmunday** [comment]
Version 4.5 released.
