### ISSUE TITLE
Function to get Friendly Username

### ISSUE THREAD

**Issue by mrgum** [neilmunday/slurm-mail#94]
The code USER=pwd.getpwnam(job.user).pw_gecos is repeated quite a bit and not ideal for my setup

I propose adding a get_friendly_username method and a friendly_username_gecos_field that defaults to 0 then the get_friendly_username would return pwd.getpwnam(job.user).pw_gecos.split(",")[friendly_username_gecos_field]

This should work for current users but help those like us with more gecos fields (out the box I got Dear Full Name,,,,Department,email@address)

Happy to code and submit PR but thought some discussion first might be useful

https://en.wikipedia.org/wiki/Gecos_field describes the typical comma separated setup

**Comment by mrgum** [comment]
Might want to default to -1 which wouldn't split by comma, incase anyone uses the gecos field just for fullname and people have commas in their name?

**Comment by neilmunday** [comment]
@mrgum thanks for raising this issue. This [RedHat article](https://www.redhat.com/sysadmin/linux-gecos-demystified) is also a useful reference.

I think we should go with slitting by comma and taking the first element as the user's name. I'll create a 4.6 branch with some new code in for review.

I also agree that a helper function makes sense to avoid repeated code.

**Comment by neilmunday** [comment]
Fix merged into `main` branch.

**Comment by neilmunday** [comment]
Version 4.6 released.

**Comment by mrgum** [comment]
Thank you!
