### ISSUE TITLE
可以支持msmtp吗？

### ISSUE THREAD

**Issue by xuetong520** [neilmunday/slurm-mail#97]
可以支持msmtp吗？

**Comment by neilmunday** [comment]
Using Google translate:

_Can msmtp be supported?_

Answer: `msmtp` is a mail client and Slurm-Mail  is also a client. Both use SMTP to communicate with mail servers.

Therefore there is no need to use `msmtp`.

Please see [smtp-settings](https://github.com/neilmunday/slurm-mail#smtp-settings) in Slurm-Mail's README for further information about e-mail settings for Slurm-Mail.
